language: python
sudo: require
matrix:
  include:
    - python: "3.4"
      env: TOX_ENV=py34
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.5"
      env: TOX_ENV=py35-ipython
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.7"
      env: TOX_ENV=py37
    - python: "3.8"
      env: TOX_ENV=py38
    - python: "3.9"
      env: TOX_ENV=py39
    - python: "3.6"
      env: TOX_ENV=lint
    - python: "3.6"
      env: TOX_ENV=doc
addons:
  apt:
    packages:
      - pkg-config 
      - libsmi2-dev 
      - libsnmp-dev 
      - snmp-mibs-downloader 
      - ncurses-term
install:
  - pip install tox coveralls
before_script:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
